# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Wusi Static
tagline:          The Static Files
url:              http://getpoole.com
paginate:         1
baseurl:          http://wusihq.github.io/wusi-static/
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wusiHQ/wusi-static
