# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            无私轻生活
tagline:          在线客服
url:              http://static.wusi.com
paginate:         1
baseurl:          http://wusihq.github.io/wusi-static/
icp:			  ICP-02394102
author:
  name:           Christopher Yeung
  url:            https://wusi.com
  email:          tech@wusi.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wusiHQ/wusi-static
